#!/bin/bash
# 
#
#
# *********************************************************************
# *
# * Sean Embry SWE
# *
# * Revision list here:
# * 2023-03-08-000 Notes
# * 2023-03-08-000 HOURS: SWE 1.00 
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
thdld="www north east south west mail db01 db02 vpn01 vpn02 fw01 fw02 rdp01 rdp02"

# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

# ****************
# * BODY OF WORK *
# ****************

#!/bin/bash
# dns-test - check SWE standard DNS entries
if [ -z $1 ]
then
	dn=`hostname`
	read -p "Host to check is $dn or enter: " domain
		if [ -z ${domain} ] 
		then
			domain=${dn}
		fi
else
	domain=$1
fi

echo "${domain}"
for i in $thdld
do
	echo $i.${domain}

done
