#!/bin/bash
# 
# Give a domain list with the standard thrid level domains and again all on one line for certbot
#
# *********************************************************************
# *
# * Sean Embry SWE
# *
# * Revision list here:
# * 2023-03-08-000 Notes
# * 2023-03-08-000 HOURS: SWE 1.00 
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
thdld="db01 db02 east fw01 fw02 mail north rdp01 rdp02 south vpn01 vpn02 west ww1 ww2 www"

# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

# ****************
# * BODY OF WORK *
# ****************

#!/bin/bash
# dns-test - check SWE standard DNS entries
if [ -z $1 ]
then
	dn=`hostname`
	read -p "Host to check is $dn or enter: " domain
		if [ -z ${domain} ] 
		then
			domain=${dn}
		fi
else
	domain=$1
fi

echo "${domain}"
for i in $thdld
do
	echo $i.${domain}

done

echo -e ""

echo -e "${domain}, \c" >> /tmp/dnt.${_dte}

for i in  $thdld

do
	echo -e "$i.${domain}, \c"
done >> /tmp/dnt.${_dte}
outer=`cat /tmp/dnt.${_dte}`
echo ${outer:0:-2}
rm /tmp/dnt.${_dte}
echo -e "\n"
