#!/bin/bash
# 
#
#
# *********************************************************************
# *
# * Sean Embry
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
# IANA officially supported top level domains:
# https://data.iana.org/TLD/tlds-alpha-by-domain.txt
#
# *********************************************************************
# TODOS
# Verify the TLD is listed as in the notes. Ensure the list is pulled no more
# than once per day.
#
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
_ytd=`date +%Y%m%d`

# **********************
# * RESOLVE VAR ISSUES *
# **********************

if [ $# -eq 1 ]; then
	domain=$1
else
	echo "No domain name given, aborting"
	exit 90
fi



# *************
# * FUNCTIONS *
# *************

function check_preq()
{
if [ ! -f ~/.email-pass ];then
	echo "[client]
	user=your-sql-user
	password=your-sql-user-password" > ~/.email-pass
	chmod 600 ~/.email-pass
	echo "Please update ~/.email-pass with correct credentials."
	echo "You are going to have problems until this is fixed"
	exit 83
fi
}

function delete_domain()
{
actid=`mysql --defaults-extra-file=~/.email-pass -N <<EOF
delete from mailserver.virtual_domains where name = '${domain}';
EOF`
echo $?
}

# ****************
# * BODY OF WORK *
# ****************

check_preq
delete_domain
