#!/bin/bash

if [ $# -eq 2 ]; then
        email=$1
        password1=$2
fi
function check_preq()
{
if [ ! -f ~/.email-pass ];then
	echo "[client]
	user=your-sql-user
	password=your-sql-user-password" > ~/.email-pass
	chmod 600 ~/.email-pass
	echo "Please update ~/.email-pass with correct credentials."
	echo "You are going to have problems until this is fixed"
	exit 83
fi
}

function change_account()

{
actid=`mysql --defaults-extra-file=~/.email-pass -N <<EOF
select id from mailserver.virtual_users where email = '${email}';
EOF`

	if [ -z ${actid} ]
	then
        	echo "Sorry, bad username";
        	exit 80
	fi
res=`mysql --defaults-extra-file=~/.email-pass -N <<EOF
update mailserver.virtual_users set password = TO_BASE64(UNHEX(SHA2('${password1}', 512))) where id = '${actid}';
EOF`
echo "Password changed"
# exit 0
}

function manual_change()
{
read -p "Enter email address to change password: " email
actid=`mysql --defaults-extra-file=~/.email-pass -N <<EOF
select id from mailserver.virtual_users where email = '${email}';
EOF`

if [ -z ${actid} ]
then
	echo "Sorry, bad username";
	exit 80
fi

echo ${actid}

read -s -p "Please enter new password for ${email}: " password1
echo ""
read -s -p "Please re-enter new password for ${email}: " password2
echo ""
if [ ${password1} != ${password2} ]
then
	echo "Passwords must match and not be empty"
	exit 99
fi

res=`mysql --defaults-extra-file=~/.email-pass -N <<EOF
update mailserver.virtual_users set password = TO_BASE64(UNHEX(SHA2('${password1}', 512))) where id = '${actid}';
EOF`
echo "Password for account ${email} changed"
}
# ***********
# * W O R K *
# ***********

check_preq

if [ -z ${password1} ]; then
	manual_change
else
	change_account
fi

