#!/bin/bash
# findrelease - returns which release and version is being run
#
#
# *********************************************************************
# *
# * Sean Embry	SWE
# *
# * Revision list here:
# * 2023-03-04		Notes initial build out
# * 2023-03-04		HOURS: SWE 1.00 
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# * YYYY-MM-DD-xxx
# * YYYY-MM-DD-xxx
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
# /etc/os-release         [On Debian, Ubuntu and Mint]
# /etc/os-release         [On RHEL/CentOS/Fedora and Rocky Linux/AlmaLinux]
# /etc/os-release         [On Alpine Linux]
# /etc/os-release         [On Arch Linux]
# /etc/SuSE-release       [On OpenSUSE]
# /etc/gentoo-release     [On Gentoo Linux]

# Update symbolic links of the system libraries
# sudo ldconfig
# Reload the systemd manager, and apply the new systemd service (guacd)
# sudo systemctl daemon-reload
# 
# 
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
_PWLIMIT=\&\:\~\?\;\:\[\]\{\}\.\'\%\"\*\(\)\\\/\|
_guac_port=4822
_guac_dir=/etc/guacamole
_usr="guac"
_usrpass=`pwgen 21 1`
_guac_key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCzGJusEOkrQzUtQTfcwJVR2FTv43I6s+2FY3MYb1v+vuTkQ5cTKpBB61mfDLRlZK6DNi4sX44Xw5/MciknJqV2FubLK5yswVy5+cseZ+nWvtWG1AnyYNdlcbIXBMDxFXC5ErsCPGMdUp6v3O+LBgcgC33z4uNL6hzXLs9OnwmrkDxuccWRtPJZidMRSqO77fitNrWGCUvca+1auzz5Q3ka2xLfYTFsgOIzugZDjkKomYwCvEWhtAvw/lThXGlc8trkpjLDwd9f7bi3X9qAjyKIRo78kN8G5YYhmF3vv6SlsT+y8qeR6iqcSIjb7uzTrc0brBYuhLHqYijsJ4UCdxw44Z90nvP+WXO3Ge+1HRxKLmKg2MbDR77/ro6c5+Cw67b/FWEiJWR9A/qDZHkyPus6qsdonsTqFEp7NGFCUof2MfabR2EkQDCEk2usYbdZCNKw/1JTJo2lpVuG0xonvZbYQl7x9H3CQ9N+KMykLX9Xi6mvoOO7D4WNbxAYNlgX0AIkUU+dzl13D26V7u1sUePkB7vvw6BeO7fBqK6ME1POZW1YK7280joGYt8uf6fCgQjok0dRowJ5aOyZpHz88EfDqUE0EBoZ+FTBq2lrAZxvg1tLboZb/45e4x1mKljNcIZOYP2ldnz3bskRYMThwjCn5cSfPUgGIRAB5eOhK4wyIw=='

# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

function inst_guac()
{

inst_guac="build-essential libcairo2-dev libjpeg-turbo8-dev libpng-dev libtool-bin uuid-dev libossp-uuid-dev wget apt-transport-https gnupg2 software-properties-common openjdk-11-jdk tomcat9 tomcat9-admin tomcat9-common tomcat9-user apache2 make libavcodec-dev libavformat-dev libavutil-dev libswscale-dev freerdp2-dev libpango1.0-dev libssh2-1-dev libtelnet-dev libvncserver-dev libwebsockets-dev libpulse-dev libssl-dev libvorbis-dev libwebp-dev"
inst_mail="postfix postfix-mysql dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-mysql mysql-server"
inst_web="certbot apache2 php php-curl php-xml libapache2-mod-php php-mysql php-mbstring mysql-server"

apt update
apt upgrade -y
apt install -y ${inst_guac}
apt install -y ${inst_web}

}

function guac_config()
{

if [ ! -d ${_guac_dir} ]
then
	mkdir -p ${_guac_dir}/{extensions,lib}
	touch ${_guac_dir}/{guacamole.properties,guacd.conf}
else
	read -p "Guacamole directoy detected, giving you the chance to bail out with <ctrl-C>" trash
fi

netstat -nltup | grep -s ${_guac_port}

inuse=$?
if [ ${inuse} -eq 0 ]
then
	read -p "Port ${_guac_port} detected in use, giveing you the chance to bail out with <ctrl-C>" trash
	echo "Moving Guacamole to port 4922 from default of 4822"
	guac_port=4922
fi

unset $inuse

# remember to enter ${_guac_port} into config below.
echo "
#
# guacd configuration file
#

[daemon]

pid_file = /var/run/guacd.pid
log_level = info

[server]

bind_host = localhost
bind_port = ${_guac_port}

#
# The following parameters are valid only if
# guacd was built with SSL support.
#

[ssl]

server_certificate = /etc/ssl/certs/guacd.crt
server_key = /etc/ssl/private/guacd.key
" > ${_guac_dir}/guacd.conf

echo 'GUACAMOLE_HOME=/etc/guacamole' >> /etc/default/tomcat9

}

function passwords()
{

# passwords for SQL
domain=`uname -n`
SQLpass=`pwgen -syr ${_PWLIMIT} 10 1`
SQLadmin=`pwgen -syr ${_PWLIMIT} 10 1`
SQLmail=`pwgen -syr ${_PWLIMIT} 10 1`
echo -"

OK, I've got defaults for ya.
Domain name is being set to: ${domain} for MySQL
SQLroot pass is:          ${SQLpass}
"

read -p "To change them, enter anything. To keep these, press enter" trash
	if [ ! -z ${trash} ]
	then
		read -p "SQL ROOT password: " SQLpass
	fi
unset trash
echo "Writing passwords to ~/mkSQL.pass"
if [ -f ~/mkSQL.pass ]
	then
	echo "backing up ~/mkSQL.pass to ~/mkSQL.pass.${_dte}"
	fi
echo "
SQL root password ${SQLpass}
" > ~/mkSQL.pass

echo "[client]
user=root
password=${SQLpass}" > ~/.MKSQL-root

chmod 600 ~/mkSQL.pass ~/.MKSQL-root

}

function debconfsetMySQL()
{
echo "mysql-server mysql-server/root_password password ${SQLpass}" | debconf-set-selections
echo "mysql-server mysql-server/root_password_again password ${SQLpass}" | debconf-set-selections
# after install, run echo PURGE | debconf-communicate <package> to secure things and not leave landminds for unwary.
}

function debconfsetMariaDB()
{
debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password password ${SQLpass}'
debconf-set-selections <<< 'mariadb-server-5.5 mysql-server/root_password_again password ${SQLpass}'
}

function make-user()
{
echo "user ${_usr} password is ${_usrpass}"
useradd -U -G sudo -d /home/${_usr} -s /bin/bash -m -k /etc/skel -p $(echo ${_usrpass} | openssl passwd -1 -stdin) ${_usr}
mkdir /home/${_usr}/.ssh
echo ${_guac_key} > /home/${_usr}/.ssh/authorized_keys
chown -R "${_usr}:${_usr}" /home/${_usr}
chmod -R 700 /home/${_usr}/.ssh
}

function go-sean()
{

	if [ -f /root/go-sean ]
	then
		if [ ! -d /guac ]
		then
			mkdir /guac
			chmod 777 /guac
		fi

		scp -P 4822 root@mygeekisp.com:/guac/* /guac/
	fi
cp /guac/guacamole-server-1.5.0.tar.gz /home/${_usr}
}

# ****************
# * BODY OF WORK *
# ****************

check_release
make-user
inst_guac
guac_config
passwords
debconfsetMySQL
make-user

echo 'PURGE' | debconf-communicate mysql-server 
echo 'PURGE' | debconf-communicate "mariadb-server-5.5"
ldconfig
daemon-reload
sudo systemctl enable guacd
sudo systemctl start guacd
sudo systemctl status guacd

echo "Now log in as the guac user, and ./configure --with-init-dir=/etc/init.d
