#!/bin/bash
# indexer - make an HTML index.html file for a subdir and below of all movies, with a .png of it as the click image.
#
#
# *********************************************************************
# *
# * <NAME> <INITALS>
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes: Initial build
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
_movietypes="mkv m4v mp4 mov"
# _docroot=`apache2ctl -t -D DUMP_VHOSTS | grep -m1 '80' | awk '{print $3}' | sed 's/(//' | sed 's/:/ /' | awk '{print $1}' | grep 'DocumentRoot' $a | awk '{print $2}'`
pthtemp="/tmp"
pth='.'
# fqdn="http://pinas.home.arpa/"
fqdn="./"
fndmed=0
# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

function filelists()
{
find ${pth} -maxdepth 1 -type f -print | sed 's/\.\///' > ${pthtemp}/indexer-list.${_dte}

while read filenm
do
	filenm1=${filenm::-4}
	echo "$filenm1" >> "${pthtemp}"/indexer-bare."${_dte}"
done < "${pthtemp}"/indexer-list."${_dte}"
}

function gotpng()
{
	true
}

function gotvid()
{

# for i in $_movietypes
# do
	# echo $i
# done

while read bare
do
	for mvt in $_movietypes
	do
		if [ -f "${bare}"."${mvt}" -a -f "${bare}".png ]
		then	
			### echo ""${bare}"."${mvt}" "${bare}".png"
			echo "<a href="\"$fqdn${bare}"."${mvt}"\"><img src=\"${fqdn}"${bare}".png\" width=\"32%\" height=\"42%\"></a>"
                        # echo "<a href="\"$fqdn${bare}"."${mvt}"\"><img src=\"${fqdn}"${bare}".png\" width=\"24%\" height=\"24%\"></a>"
                        # echo "<a href="\"$fqdn${bare}"."${mvt}"\"><img src=\"${fqdn}"${bare}".png\" width=\"19%\" height=\"19%\"></a>"
                        # echo "<a href="\"$fqdn${bare}"."${mvt}"\"><img src=\"${fqdn}"${bare}".png\" width=\"16%\" height=\"16%\"></a>"
		fi
	done
if [ ! -f "${bare}".png ]
then
	echo ""${bare}" has no .png" >> /tmp/indexer-nopng.`date +%Y%m%d`
fi

done < "${pthtemp}"/indexer-bare."${_dte}"

}

function remtemp()
{
	rm "${pthtemp}"/indexer-list."${_dte}" "${pthtemp}"/indexer-bare."${_dte}"
}

# ****************
# * BODY OF WORK *
# ****************

rm -f /tmp/indexer-nopng.`date +%Y%m%d`

filelists
gotvid
remtemp
