#!/bin/bash
# indexer - make an HTML index.html file for a subdir and below of all movies, with a .png of it as the click image.
#
#
# *********************************************************************
# *
# * <NAME> <INITALS>
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes: Initial build
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * YYYY-MM-DD-xxx	Notes:
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# *			
# *			
# *			
# *			
# *			
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
_movietypes="mkv m4v mp4 mov"
pthtemp="/tmp"
pth='.'
fqdn=""
fndmed=0
# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

function filelists()
{
find ${pth} -type f -print | sed 's/\.\///' > ${pthtemp}/indexer-list.${_dte}

while read filenm
do
	filenm1=${filenm::-4}
	echo "$filenm1" >> "${pthtemp}"/indexer-bare."${_dte}"
done < "${pthtemp}"/indexer-list."${_dte}"
}

function gotpng()
{
	true
}

function gotvid()
{

for i in $_movietypes
do
	echo $i
done

while read bare
do
	for mvt in $_movietypes
	do
		if [ -f "${bare}"."${mvt}" -a -f "${bare}".png ]
		then	
			### echo ""${bare}"."${mvt}" "${bare}".png"
			echo "<a href=\"http://"${bare}"."${mvt}"\"><img src=\"http://"${bare}".png\" width=\"33%\" height=\"33%\"></a>"
		fi
	done
if [ ! -f "${bare}".png ]
then
	echo ""${bare}" has no .png" >> /tmp/indexer-nopng.`date +%Y%m%d`
fi

done < "${pthtemp}"/indexer-bare."${_dte}"

}

function remtemp()
{
	rm "${pthtemp}"/indexer-list."${_dte}" "${pthtemp}"/indexer-bare."${_dte}"
}

# ****************
# * BODY OF WORK *
# ****************

rm -f /tmp/indexer-nopng.`date +%Y%m%d`

filelists
gotvid
remtemp

exit 0

for mv in `ls -c1 *.png`
do
mv1=`basename $mv .png`
echo $mv1
done | sort > /tmp/swe
echo "<meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate">
<meta http-equiv="Pragma" content="no-cache">
<meta http-equiv="Expires" content="0">
<center>"

while read mv1
do
# echo "<a href=\"file://$pth/$mv1.m4v\"> <img src=\"file://$pth/$mv1.png\" width=\"33%\" height=\"33%\"></a>" 
echo "<a href=\"http://pinas.home.arpa/$pth/$mv1.m4v\"><img src=\"http://pinas.home.arpa/$pth/$mv1.png\" width=\"33%\" height=\"33%\"></a>" 
done < /tmp/swe
echo "</center>"
rm /tmp/swe
