#!/bin/bash
# Make an email server Mark II
#
#
# *********************************************************************
# *
# * Sean Embry
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes
# * 2022-01-12-000	Adapt from mkmail 
# *			reformat to maintainability format standards
# *
# *
# *
# *
# *
# *
# *
# *
# *
# *
# *
# *********************************************************************
# NOTES:
# Keep in mind to abstract so that new ISPs can easily be added.
#
#
#
#
# *********************************************************************
# TODO'S
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`
_MkMailVer='2.0'
_MkMailLog='/var/log/mkmail/${_MkMailVer}'

# **********************
# * RESOLVE VAR ISSUES *
# **********************


# *************
# * FUNCTIONS *
# *************

function hostme()
{
	domain=`uname -n`
	read -p "Current hostname is ${domain} - if this is incorrect, enter new host name" newhost
		if [ ! -z ${newhost} ]
		then
			echo "Changing hostname to ${newhost}"
			read -p "You'll need to update the /etc/host file yourself"
			hostname="${newhost}"
			${domain}=${newhost}
			
			hnc=`which hostnamectl`
			if [ ! -z ${hnc} ]
				then
				hostnamectl set-hostname ${newhost}
			fi

		else
			echo "Keeping domain ${domain}"
		fi

}

function debconfset()
{
debconf-set-selections $postfix stuff

debconf-set-selections <<< 'mysql-server mysql-server/root_password password' ${mypass}
debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password' ${mypass}
debconf-set-selections <<< "postfix postfix/mailname string ${domain}"
debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"

}
# ****************
# * BODY OF WORK *
# ****************

hostme


# Catchall poison pill to stop fall throughs
echo "ABORTING" ; exit 99

clear; echo -e "\n \n Setting up email "; read -p "<ENTER> to continue, ^C to abort: " trash

# Check to see if the system has had the domainname set
#if [ ! -e /etc/hosts.bak ]
#then
#	read -p  'Enter domain name: ' domainname
#	echo $domainname
#	cp /etc/hosts /etc/hosts.bak
#	cp /etc/hostname /etc/hostname.bak
#	sed -i 's/localhost/'$domainname'/g' /etc/hosts
#	sed -i 's/localhost/'$domainname'/g' /etc/hostname
#
#	echo "Rebooting the system for changes to take effect"
#	read -p "Press enter to reboot , press ^C to abort"; # shutdown -r now
#else
#	echo "Changes seen"
#	domainname=`hostname`
#	echo $domainname
#fi

trash=`hostname`
read -p "Hostname is currently $trash, enter a host name to change it if desired: " newhost

if [ ! -z $newhost ]
	then
		echo "SETTING host name to: $newhost"
		hostname $newhost
fi
unset newhost
echo -e "Hostname is: \c"; hostname
pwgen=`which pwgen`

	if [ -z $pwgen ]
		then
			echo -e "\a\n******\nLooks like pwgen isn't installed or is not in the path please correct\n******"
		else
			propass=`pwgen  16 1`
			echo "Proposed password (you can change it next step) is: " $propass
	fi

read -p "Enter desired Msql Password: " mypass
read -p "re-enter desired Msql Password: " mypass2
	if [ -z $mypass ] || [ -z $mypass2 ]
		then
		echo "Using suggested password $propass "
		mypass=$propass
		mypass2=$propass
	fi

	if [ $mypass != $mypass2 ]	
		then
		echo -e "\a******password mismatch******\n" ; exit 99
	fi
unset mypass2 propass
echo "Mysql Using password: $mypass " >> ~/.mkmail
chmod 600 ~/.mkmail
exit 0
# debconf-set-selections <<< "postfix postfix/mailname string $domainname"
# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password'
# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password your_password'
# sudo apt-get -y install mysql-serverdebconf-set-selections <<< "postfix postfix/main_mailer_type string Internet Site"

# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password your_password'
# sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password your_password'
###sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password' $mypass
###sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password' $mypass

###sudo apt-get install -y postfix postfix-mysql dovecot-core dovecot-imapd dovecot-pop3d dovecot-lmtpd dovecot-mysql mysql-server
