#!/bin/bash
# mksite2 - revision to original 
# 
#
#
# *********************************************************************
# *
# * Sean Embry
# * 2021-09-05
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes
# * 2021-09-09-000	rewrite of original script for portability
# * 2021-10-01-000	reorder for funtions
# * 2021-10-15-000      Bug touchups
# * 2021-11-30-000	commenting code
# * 2021-12-02-000	discussed with jbd, logic change for large virtual farms
# * 2021-12-10-000	discussed log rotation with cjm, pointed to need to allow
# * 			customers a directory where they can d.l their own logs
# *			be sure to change ownership so only admin or cust can get them
# *
# * 2021-12-19-000	do default HTML files
# * 2021-12-20-000	common area for .htpasswd files ${secrets}${domain}
# * 2021-12-23-000	logic fix up neaten up, commenting
# * 2021-12-25-000	logic fix up for incorrect directories and fix non braced variables
# * 2021-12-25-001	update revision list
# * 2021-12-25-002	add comment for .htpass, add default .htaccess domain variables in script
# * 2021-12-26-000	add logic to prefix a site config with a number
# *			add robots and humans text files
# *
# * 2021-12-27-000	Test Certbot workings
# * 2021-12-27-001	Fix SSL stanza for missing directory location
# * 2021-12-28-000	Add HTTP to HTTPS redirect in comment for the VS
# * 2021-12-28-001	Add CERT bot instructions
# * 2021-12-31-000	Add default 000-default logic for port 80 and self signed cert
# * 2022-01-01-000	Tune back so webpages are NOT created under /var/www/html/, but /var/www/
# *			per Apache security updates
# *
# * 2022-01-01-001	PGMR: SWE HoursWasted: 1.25
# * 2022-01-01-001	PGMR: SWE HoursSpent: 0.25
# *			Bad words bad words bad words. Rediscoved a gotcha in apache2 vis-a-vi default sites that I forgoten about!
# *			And YES! you WANT a default site for bots that use the IP address instead of a named virtual host!
# *			The fix is to add 
# *			ServerName :80 to the standard default site /etc/apache2/sites-avalable/000-default.conf
# *			ServerName :443 to the ssl default site /etc/apache2/sites-available/default-ssl.conf
# *			Added warnings to the configs for sites created with this script
# *
# * 2022-01-05-000	Correct file name for certbot.notes and correct missing standard aliases
# * 2022-01-05-001	Think about moving standard aliases to a defined stanza and look for a file to override it for a domain
# *
# *
# * Certbot docs (as of 2021-12-31) https://eff-certbot.readthedocs.io/en/stable/using.html
# * self signed certs: (bad idea) https://www.baeldung.com/openssl-self-signed-cert
# *********************************************************************
#
# project notes:
# as with a lot of bash scritps it is helpful to see variable substitution for debug with
# bash -x ./script-name
# or uncomment
# set -x
# TO DO
# Fix loging rotation scripts for apache so they are compressed
# make user for each new domain and set ownership rights to their web dir secrets and logs
# certbot certonly --dry-run -d vixenfakenews.com,www.vixenfakenews.com,north.vixenfakenews.com,east.vixenfakenews.com,south.vixenfakenews.com,west.vixenfakenews.com,mail.vixenfakenews.com
#

# Most variable not set in the script go here
# where we put our virtual configs
basedir=/etc/apache2/sites-available

#directory for crypto bags like .htpass
secrets=/usr/local/etc/apache

# Virtual server log director
vslog=/var/log/apache2/

# what extention we're going to give to backup files
dte=`date +%s`

# havessl 0 = no 1 = yes
havessl=0

# base directory for websites
web='/var/www'

# pass in cmd line parms
domain=$1

#############
# FUNCTIONS #
#############

# Tests for Apache
function baseapache()
{
apwhich=`which apache2`
	if [ -z ${apwhich} ]
	    then
		echo -e "Apache2 doesn't seem to be installed or in my path:\n${PATH}"
		exit 100
	    else
		apwhich=`apache2 -v`
	fi

if [ ! -f /etc/apache2/mods-enabled/ssl.conf ]
	then
		echo "
	   Whoops! Looks like you don't have ssl configured yet.
	   Press <ENTER> to continue, or <CTRL><C> to abort and do:
	sudo a2enmod ssl 
	   and don't forget to 
	sudo apache2ctl restart
"

		read -p "<CTRL>+<C> to exit, <ENTER> to continue without a SSL virtual server stanza"
	else

		havessl=1
	fi


# Grab the domain name if not from command line
if [ -z $domain ]
	then
		read -p "FQDN: " domain
fi

if [ -z $domain ]
    then
	echo "Please enter a FQDN"
	exit 102
fi
}

function dircheck()
{
# directory for web site
	if [ ! -d ${web}/${domain} ]
        then
		echo "${web}/${domain}"
		mkdir ${web}/${domain}
        fi

# directory for logs for the domain
	if [ ! -d /var/log/apache2/${domain} ]
	then
		echo "/var/log/apache2/${domain}"
		mkdir /var/log/apache2/${domain}
        fi
#### need to create a basic auth sub dir
	if [ ! -d ${secrets} ]
	then
		echo "${secrets}"
		mkdir ${secrets}
	fi

	if [ ! -d ${secrets}/${domain} ]
	then
		echo "${secrets}/${domain}"
		mkdir ${secrets}/${domain}
        fi

#### need to check for a .htpass file for secrets

# back up an exsisting config
if [ -f ${basedir}/${domain}.conf ]
        then
	        cp ${basedir}/${domain}.conf ${basedir}/${domain}.conf.${dte}
fi

# back up an exsisting ssl config
if [ -f ${basedir}/${cnt}${domain}-ssl.conf ]
        then
	        cp ${basedir}/${domain}-ssl.conf ${basedir}/${domain}-ssl.conf.${dte}
fi

}

function countsites()
{
# orphaned at the moment. Be sure to go back and add ${cnt}-${domain} everywhere before use
	if [ -d /etc/apache2 ] && [ -d /etc/apache2/sites-available ]
	then

		if [ -f /etc/apache2/sites-available/count ]
		then
			cnt=`cat /etc/apache2/sites-available/count`
		else
			echo "1" > /etc/apache2/sites-available/count
			cnt=0
		fi

	cnt=`expr ${cnt} + 1`
	echo $cnt > /etc/apache2/sites-available/count
	cnt=`printf "%0*d-" 3 $cnt`

	else
		echo "Something is wrong with /etc/apache2/site-avaliable path"
		exit 200
	fi
}

function makeitredir()
{
	echo "
<VirtualHost *:80> 
ServerName example.com
ServerAlias www.example.com
Redirect permanent / https://${domain}/
</VirtualHost>
" > ${basedir}/${cnt}${domain}.conf
}

function makeit()
{
echo "
# PROBLEM? - If you have 000-default.conf enabled, you might get that instead of your intended site. If so, what is going on is you need to add:
# PROBLEM? - ServerName :80 to the /etc/apache2/sites-avaialbe/000-default.conf file.
#####   TO REDIRECT non-ssl traffic to ssl, uncomment below and comment out the port 80 virtual host
#####<VirtualHost *:80> 
#####	ServerName example.com
#####	ServerAlias www.example.com
#####	Redirect / https://${domain}/
#####</VirtualHost>
##### comment from HERE to below
<VirtualHost *:80>

	# Please put your .htpass file here: ${secrets}/${domain} for basic auth
    ServerAdmin webmaster@${domain}
    DocumentRoot ${web}/${domain}
    ServerName ${domain}
    ServerAlias www.${domain} north.${domain} east.${domain} south.${domain} west.${domain} mail.${domain} db01.${domain} db02.${domain}
    ErrorLog \${APACHE_LOG_DIR}/${domain}/error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}/access.log combined
    RewriteEngine On

    <Directory ${web}/${domain}>
	    Options Indexes FollowSymLinks MultiViews
	    AllowOverride FileInfo AuthConfig
	    Order allow,deny
	    allow from all

	    ErrorDocument 404 /error404.html
	    # ErrorDocument 500 /custom_50x.html
	    # ErrorDocument 502 /custom_50x.html
	    # ErrorDocument 503 /custom_50x.html
	    # ErrorDocument 504 /custom_50x.html


	    #####################################
	    # except a directory from this rule #
	    #####################################
	    #   RewriteCond %{REQUEST_URI} !/check/

	    ################################
	    # except a file from this rule #
	    ################################
	    #   RewriteCond %{REQUEST_URI} !/check/index.html

	    # These are HTML request methods we will not allow
	    RewriteCond %{REQUEST_METHOD} ^(POST|PUT|DELETE|PATCH|HEAD|CONNECT|TRACE|TRACK|OPTIONS)
	    RewriteRule .* - [F]
    </Directory>

</VirtualHost>
##### STOP commenting out here for a redirect from above
" 
} > ${basedir}/${cnt}${domain}.conf

function makeitssl()
{
echo "
<VirtualHost *:443>
# PROBLEM? - If you have default-ssl.conf enabled, you might get that instead of your intended site. If so, what is going on is you need to add:
# PROBLEM? - ServerName :443 to the /etc/apache2/sites-avaialbe/default-ssl.conf file.
	###
	# Free certs with certbot - instructions as of 2021-12-28 - https://certbot.eff.org/instructions
	# Be sure to tip EFF for their help now, hear? (ME TOO! TIP ME!)
	###
	# grab certificates with cert bot 
# Docs (as of 2021-12-31) https://eff-certbot.readthedocs.io/en/stable/using.html
# TEST: certbot certonly --dry-run -d ${domain},www.${domain},north.${domain},east.${domain},south.${domain},west.${domain},mail.${domain},db01.${domain},db02.${domain}
# FORREAL: certbot certonly -d ${domain},www.${domain},north.${domain},east.${domain},south.${domain},west.${domain},mail.${domain},db01.${domain},db02.${domain}
	#########
	# ALERT # Do not mix your domains on a virtual web server for certificats because it leakes all the domain names if they look at the cert
	#########
	# Please put your .htpass file here: ${secrets}/${domain} for basic auth
	
    ServerAdmin webmaster@${domain}
    DocumentRoot ${web}/${domain}
    ServerName ${domain}
    ServerAlias www.${domain} north.${domain} east.${domain} south.${domain} west.${domain} mail.${domain} db01.${domain} db01.${domain}
    ErrorLog \${APACHE_LOG_DIR}/${domain}/ssl-error.log
    CustomLog \${APACHE_LOG_DIR}/${domain}/ssl-access.log combined
    SSLEngine on
    RewriteEngine On
    SSLCertificateFile /etc/letsencrypt/live/${domain}/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/${domain}/privkey.pem

    <Directory ${web}/${domain}>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride FileInfo AuthConfig
            Order allow,deny
            allow from all

            ErrorDocument 404 /error404.html
            # ErrorDocument 500 /custom_50x.html
            # ErrorDocument 502 /custom_50x.html
            # ErrorDocument 503 /custom_50x.html
            # ErrorDocument 504 /custom_50x.html


            #####################################
            # except a directory from this rule #
            #####################################
            #   RewriteCond %{REQUEST_URI} !/check/

            ################################
            # except a file from this rule #
            ################################
            #   RewriteCond %{REQUEST_URI} !/check/index.html

	    # These are HTML request methods we will not allow
            RewriteCond %{REQUEST_METHOD} ^(POST|PUT|DELETE|PATCH|HEAD|CONNECT|TRACE|TRACK|OPTIONS)
            RewriteRule .* - [F]
    </Directory>

</VirtualHost>
"
} > ${basedir}/${cnt}${domain}-ssl.conf

function makeitdefault()
{
echo "
# This is strictly for making a default port 80 to handle domains not otherwise specified
<VirtualHost *:80>
    ServerAdmin forgetit@example.com
    DocumentRoot /var/www/html/default
    ServerName :80
    ErrorLog \${APACHE_LOG_DIR}/default/error.log
    CustomLog \${APACHE_LOG_DIR}/default/access.log combined
    RewriteEngine On

    <Directory /var/www/html/default
	    Options Indexes FollowSymLinks MultiViews
	    AllowOverride FileInfo AuthConfig
	    Order allow,deny
	    allow from all
	    # These are HTML request methods we will not allow
	    RewriteCond %{REQUEST_METHOD} ^(POST|PUT|DELETE|PATCH|HEAD|CONNECT|TRACE|TRACK|OPTIONS)
	    RewriteRule .* - [F]
    </Directory>

</VirtualHost>
" 
}

function makedefaultssl()
{
echo "
<VirtualHost *:443>
    ServerAdmin forgetaboutit@example.com
    DocumentRoot /var/www/html/default
    ServerName :443
    ErrorLog \${APACHE_LOG_DIR}/default/ssl-error.log
    CustomLog \${APACHE_LOG_DIR}/default/ssl-access.log combined
    SSLEngine on
    RewriteEngine On
    # These need changing to someplace other than /etc/letsencrypt
    # SSLCertificateFile /etc/letsencrypt/live/${domain}/fullchain.pem
    # SSLCertificateKeyFile /etc/letsencrypt/live/${domain}/privkey.pem

    <Directory /var/www/html/default>
            Options Indexes FollowSymLinks MultiViews
            AllowOverride none
            Order allow,deny
            allow from all
            RewriteCond %{REQUEST_METHOD} ^(POST|PUT|DELETE|PATCH|HEAD|CONNECT|TRACE|TRACK|OPTIONS)
            RewriteRule .* - [F]
    </Directory>

</VirtualHost>
"
}

function defaultfiles()
{
	if [ ! -f ${web}/${domain}/index.html ]
	then
		echo "
<!doctype html>
<html>
  <head>
    <title>Welcome to ${domain}</title>
  </head>
  <body>
    <p><center><H1>Hello!</H1><BR>As you can see, we are setting up our server ${domain}</p>
  </body>
</html>
" > ${web}/${domain}/index.html
	fi

	if [ ! -f ${web}/${domain}/humans.txt ]
	then
		echo "
<!doctype html>
<html>
  <head>
    <title>Welcome to ${domain}</title>
  </head>
  <body>
    <p><center><H1>Hello!</H1><BR>Our team has not updated the humans.txt file for ${domain}</p>
    <p>Greetings from the creator of the mksite script, may your day be safe and productive</center>
  </body>
</html>
" > ${web}/${domain}/humans.txt
	fi

	if [ ! -f ${web}/${domain}/robots.txt ]
	then
		echo "
User-agent: *
Disallow: /DirectoriesNotToBeSearched/
" > ${web}/${domain}/robots.txt
	fi

	if [ ! -f ${web}/${domain}/error404.html ]
	then
		echo "
		<center><P><P><h1>
		We are sorry - Domain ${domain} doesn't have that web page!
		</center></h1>
" > ${web}/${domain}/error404.html
	fi
echo "certbot certonly --dry-run -d ${domain},www.${domain},north.${domain},east.${domain},south.${domain},west.${domain},mail.${domain},db01.${domain},db02.${domain}" >> ~/certbot.${domain}.notes

}

function mkselfsign()
{

# Sometimes folks do not want the snakeoil certificate - I don't know why but here is the process

echo "authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
subjectAltName = @alt_names
[alt_names]
DNS.1 = Place-Holder-Something-Is-Wrong.com" > ${secrets}/default/domain.ext

openssl req -newkey rsa:2048 -nodes -keyout ${secrets}/default/domain.key -out domain.csr -subj "/C=US/ST=Confusion/L=Confusion/O=Really Fake Key/OU=No one here/CN=thisisascam.com"
openssl req -newkey rsa:2048 -nodes -keyout ${secrets}/default/domain.key -x509 -days 365 -out ${secrets}/default/domain.crt -subj "/C=US/ST=Confusion/L=Confusion/O=Really Fake Key/OU=No one here/CN=thisisascam.com"
openssl req -x509 -sha256 -days 1825 -nodes -newkey rsa:2048 -keyout ${secrets}/default/rootCA.key -out ${secrets}/default/rootCA.crt -subj "/C=US/ST=Confusion/L=Confusion/O=Really Fake Key/OU=No one here/CN=thisisascam.com"
openssl x509 -req -CA ${secrets}/${default}/rootCA.crt -CAkey ${secrets}/default/rootCA.key -in ${secrets}/default/domain.csr -out ${secrets}/default/domain.crt -days 365 -CAcreateserial -extfile ${secrets}/default/domain.ext

}



########
# WORK #
########

baseapache
dircheck
# countsites
makeit
if [ ${havessl} -eq 1 ]
	then
	makeitssl
fi
defaultfiles
