#!/bin/bash
#  Unfutter - dedupe file systems with md5 sum
#
#
# *********************************************************************
# *
# * <NAME> <INITALS>
# *
# * Revision list here:
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: INITALS 1.25 for an hour and 15 minutes
# *			
# * 2023-05-19-000	begin
# * 2023-05-19-000	HOURS: SWE 1.25
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS:
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS:
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS: 
# *			
# * YYYY-MM-DD-xxx	Notes
# * YYYY-MM-DD-xxx	HOURS:
# *			
# *********************************************************************
# NOTES:
# varibles that start with an underscore should be set in the DEFINE VARIABLES section and not modified elsewhere.
#
#
#
#
# *********************************************************************
# TODOS
#
#
#
#
#
# *******************
# * DEFINE VARABLES *
# *******************
_dte=`date +%s`

# *****************
# * CHECK PREREQS *
# *****************

# **********************
# * RESOLVE VAR ISSUES *
# **********************

# *************
# * FUNCTIONS *
# *************

# ****************
# * BODY OF WORK *
# ****************

